apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: vault
  name: payments-app
---
apiVersion: v1
kind: Service
metadata:
  name: payments-app
  labels:
    app: payments-app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: payments-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-app
  annotations:
    kubernetes.io/service-account.name: "payments-app"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payments-app
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payments-app
    serviceAccount: payments-app
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payments-app-processor
spec:
  vaultAuthRef: payments-app
  mount: payments/secrets
  type: kv-v2
  path: processor
  refreshAfter: 60s
  destination:
    create: true
    name: payments-app-processor
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: payments-app-database
spec:
  mount: payments/database
  path: creds/payments-app
  destination:
    create: true
    name: payments-app-database
  rolloutRestartTargets:
  - kind: Deployment
    name: payments-app
  vaultAuthRef: payments-app