---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-processor
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-processor
  annotations:
    kubernetes.io/service-account.name: "payments-processor"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-processor
  labels:
    app: payments-processor
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: payments-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments-processor
      app: payments-processor
  template:
    metadata:
      labels:
        service: payments-processor
        app: payments-processor
    spec:
      containers:
        - name: payments-processor
          image: payments-processor
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_PASSWORD
              value: "payments-admin-password"