---
apiVersion: v1
kind: Service
metadata:
  name: payments-app
  labels:
    app: payments-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: payments-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-app
  annotations:
    kubernetes.io/service-account.name: "payments-app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments-app
      app: payments-app
  template:
    metadata:
      labels:
        service: payments-app
        app: payments-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payments-app"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true" # Required for termination signal
        vault.hashicorp.com/agent-cache-enable: "true" # Use cached secrets and lease from vault-agent initialization to agent
        vault.hashicorp.com/template-static-secret-render-interval: "5m" # Defaults to 5 minutes, update if you want static secrets checked more frequently

        vault.hashicorp.com/agent-inject-secret-processor: "payments/secrets/data/processor"
        vault.hashicorp.com/secret-volume-path-processor: "/vault/secrets/config/processor"
        vault.hashicorp.com/agent-inject-file-processor: "payments-app.properties"
        vault.hashicorp.com/agent-inject-template-processor: |
          payment.processor.url=http://payments-processor:8080
          {{- with secret "payments/secrets/processor" }}
          payment.processor.username={{ .Data.data.username }}
          payment.processor.password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-processor: |
          kill -TERM $(pidof java)

        vault.hashicorp.com/agent-inject-secret-database: "payments/database/creds/payments-app"
        vault.hashicorp.com/secret-volume-path-database: "/vault/secrets/config/database"
        vault.hashicorp.com/agent-inject-file-database: "payments-app.properties"
        vault.hashicorp.com/agent-inject-template-database: |
          payments.db.url=jdbc:postgresql://payments-database:5432/payments
          {{- with secret "payments/database/creds/payments-app" }}
          payments.db.username={{ .Data.username }}
          payments.db.password={{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-database: |
          kill -TERM $(pidof java)

    spec:
      serviceAccountName: payments-app
      shareProcessNamespace: true # Required for termination signal
      containers:
        - name: payments-app
          image: payments-app:java
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          command: ["/bin/sh"]
          args: ["-c", "java -XX:+UseContainerSupport -Dspring.cloud.config.server.vault.token=$(cat /vault/secrets/token) -Dspring.cloud.vault.token=$(cat /vault/secrets/token) -Djava.security.egd=file:/dev/./urandom -jar /app/spring-boot-application.jar"]
          env:
            - name: VAULT_HOST
              value: vault
            - name: CONFIG_HOME
              value: /vault/secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
          securityContext: # Required for termination signal
            runAsUser: 1000 # Required for termination signal
            runAsGroup: 3000 # Required for termination signal