---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-database
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-database
  annotations:
    kubernetes.io/service-account.name: "payments-database"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-database
  labels:
    app: payments-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: payments-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments-database
      app: payments-database
  template:
    metadata:
      labels:
        service: payments-database
        app: payments-database
    spec:
      containers:
        - name: payments-database
          image: payments-database
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres-admin-password"
            - name: POSTGRES_DB
              value: "payments"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - name: pgdata
          emptyDir: {}