version: "3.3"
services:

  payments-app:
    build: ../payments-app/java
    image: payments-app:java
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 8081:8081
    volumes:
      - ./vault-agent:/root:r
    entrypoint: ["/bin/sh"]
    command: ["-c", "java -XX:+UseContainerSupport -Dspring.cloud.config.server.vault.token=$$(cat /root/.vault-token) -Dspring.cloud.vault.token=$$(cat /root/.vault-token) -Djava.security.egd=file:/dev/./urandom -jar /app/spring-boot-application.jar"]
    environment:
      VAULT_HOST: "vault"
      CONFIG_HOME: "/root"

networks:
  vpcbr:
    name: workshop-vault-for-developers_vpcbr