services:

  vault-agent:
    image: hashicorp/vault:1.16.1
    restart: always
    command: [ 'vault', 'agent', '-config=/vault/config.hcl']
    volumes:
      - ./vault:/vault:rw
      - ./vault-agent:/vault-agent:rw
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  payments-app:
    build: ../payments-app/java
    depends_on:
      - vault-agent
    image: payments-app:java
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 8081:8081
    volumes:
      - ./vault-agent:/root:r
    entrypoint: ["/bin/sh"]
    command: ["-c", "export VAULT_TOKEN=$$(cat /root/.vault-token) && java -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom -jar /app/spring-boot-application.jar"]
    environment:
      VAULT_ADDR: "http://vault:8200"
      CONFIG_HOME: "/root/config"
      spring_profiles_active: "agent"

networks:
  vpcbr:
    name: workshop-vault-for-developers_vpcbr