version: "3.3"
services:

  vault:
    image: vault:1.11.1
    restart: always
    command: [ 'vault', 'server', '-dev', '-dev-listen-address=0.0.0.0:8200']
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "some-root-token"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  payments-database:
    build: ../payments-database
    image: payments-database
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres-admin-password"
      POSTGRES_DB: "payments"

  payments-processor:
    build: ../payments-processor
    image: payments-processor
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 8080:8080
    environment:
      ADMIN_PASSWORD: "payments-admin-password"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16