version: "3.3"
services:

  payments-app:
    build: ../payments-app/java
    image: payments-app:java
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 8081:8081
    volumes:
      - ./vault-agent:/root:r
    entrypoint: ["/bin/sh"]
    command: ["-c", "export VAULT_TOKEN=$$(cat /root/.vault-token) && java -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom -jar /app/spring-boot-application.jar"]
    environment:
      VAULT_ADDR: "http://vault:8200"
      CONFIG_HOME: "/root/config"

networks:
  vpcbr:
    name: workshop-vault-for-developers_vpcbr