payment.processor.url=${PAYMENTS_PROCESSOR_URL}
{{- with secret "payments/secrets/processor" }}
payment.processor.username={{ .Data.data.username }}
payment.processor.password={{ .Data.data.password }}
{{- end }}