spring.config.import=vault://

spring.cloud.vault.authentication=AWS_IAM
spring.cloud.vault.aws-iam.role=payments-app
spring.cloud.vault.aws-iam.aws-path=aws

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=payments-app

spring.cloud.vault.database.enabled=true
spring.cloud.vault.database.role=payments-app
spring.cloud.vault.database.backend=payments/database

spring.cloud.vault.config.lifecycle.min-renewal=30s
spring.cloud.vault.config.lifecycle.expiry-threshold=10s

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:payments-database}:5432/payments
payment.processor.url=http://${PROCESSOR_URL:payments-processor}:8080

secrets.refresh-interval-ms=180000